#! /usr/bin/env python
"""pyMarshMorpho2D model."""

import numpy as np
from numpy.testing import assert_array_equal, assert_array_almost_equal
from landlab import RasterModelGrid
from pymarshmorpho2d import MarshEvolver


# The values in TEST_TOPO correspond to selected cells in the SWENEY data set.
TEST_TOPO = np.array(
    [-2.6093, -2.4724, -2.2384, -2.0554, -1.8425,
     -1.6818, -1.5573, -1.3660, -1.1061, -0.9180,
     -0.7152, -0.5590, -0.3962, -0.1895, -0.0287,
      0.1852,  0.3978,  0.5599,  0.7318,  0.8774,
      1.0375,  1.2519,  1.4300,  1.5350,  2.0000])

CORRESPONDING_CELL_ROWS = [
    397, 399, 400, 401, 401,
    400, 407, 402, 406, 403,
    406, 410, 407, 401, 408,
    405, 408, 406, 404, 410,
    409, 414, 419, 394, 130,
]

CORRESPONDING_CELL_COLS = [
    168, 165, 164, 163, 164,
    162, 159, 159, 161, 157,
    162, 159, 162, 157, 151,
    153, 150, 151, 152, 163,
    165, 162, 165, 222, 200
]

def test_get_water_depth():

    # Create a test grid and topography (positive above starting mean sea level)
    grid = RasterModelGrid((5, 5), xy_spacing=(2.0, 2.0))
    topo = grid.add_zeros('node', 'topographic__elevation')
    topo[:] = TEST_TOPO

    # Instantiate MarshEvolver
    mev = MarshEvolver(grid)

    # Run get_water_depth
    mev._mean_sea_level = 0.002
    mev.get_water_depth()

    # Compare computed depth with what was previously generated by the
    # original matlab version
    assert_array_almost_equal(mev._fully_wet_depth,
                              [2.6113, 2.4744, 2.2404, 2.0574, 1.8445,
                               1.6838, 1.5593, 1.4590, 1.3291, 1.2350,
                               1.1336, 1.0555, 0.9741, 0.8707, 0.7904,
                               0.6834, 0.5771, 0.4961, 0.4101, 0.3373,
                               0.2572, 0.1500, 0.0610, 0.0100, 0.0100],
                              decimal=4)
    assert_array_almost_equal(mev._water_depth,
                              [2.6113, 2.4744, 2.2404, 2.0574, 1.8445,
                               1.6838, 1.5593, 1.4590, 1.3291, 1.2350,
                               1.1336, 1.0555, 0.9741, 0.8707, 0.7904,
                               0.6834, 0.5771, 0.4961, 0.4101, 0.3373,
                               0.2572, 0.1500, 0.0610, 0.0100, 0.0000],
                              decimal=4)
    assert_array_almost_equal(mev._fully_wet_depth,
                              [2.6113, 2.4744, 2.2404, 2.0574, 1.8445,
                               1.6838, 1.5593, 1.4590, 1.3291, 1.2350,
                               1.1336, 1.0555, 0.9741, 0.8707, 0.7904,
                               0.6834, 0.5771, 0.4961, 0.4101, 0.3373,
                               0.2572, 0.1500, 0.0610, 0.0100, 0.0100],
                              decimal=4)

def test_update_vegetation_and_roughness():

    # Create a test grid and topography (positive above starting mean sea level)
    grid = RasterModelGrid((5, 5), xy_spacing=(2.0, 2.0))
    topo = grid.add_zeros('node', 'topographic__elevation')
    topo[:] = TEST_TOPO

    # Instantiate MarshEvolver
    mev = MarshEvolver(grid)

    # Run update_vegetation
    mev._mean_sea_level = 0.002
    mev.update_vegetation()

    # Compare computed depth with what was previously generated by the
    # original matlab version
    assert_array_equal(mev._veg_is_present, [False, False, False, False, False,
                                             False, False, False, False, False,
                                             False,  True,  True,  True,  True,
                                              True,  True,  True,  True,  True,
                                              True,  True,  True,  True,  True])
    assert_array_almost_equal(mev._vegetation,
                              [   0.0,    0.0,    0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0,
                                  0.0, 0.1435, 0.3963, 0.6538, 0.8048,
                               0.9391, 0.9972, 0.9910, 0.9366, 0.8520,
                               0.7183, 0.4725, 0.2102, 0.0307,    0.0],
                              decimal=4)

    # Update roughness
    mev.update_roughness()
    
    # Roughness should have default values in areas with and without veg
    assert_array_equal(mev._roughness,
                       [0.02, 0.02, 0.02, 0.02, 0.02,
                        0.02, 0.02, 0.02, 0.02, 0.02,
                        0.02, 0.10, 0.10, 0.10, 0.10,
                        0.10, 0.10, 0.10, 0.10, 0.10,
                        0.10, 0.10, 0.10, 0.10, 0.10,])
